# numpy

## array

In [2]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))
print(a.shape)# 等价于matlab的size 返回规格数组
b = np.array([[1, 2, 3], [4, 5, 6]]) #注意外层的中括号

print(b.shape)
print(b.size)#元素总数




<class 'numpy.ndarray'>
(3,)
(2, 3)
6


In [33]:
a = np.zeros((2, 2))
print(a)

b = np.ones((2, 3))
print(b)

c = np.full((2, 2), 7)
print(c)

d = np.eye(2)
print(d)

e = np.random.random((5, 3))#(0,1)
print(e)

rand_arr = np.random.randint(low=5, high=10, size=(5, 3))
print(rand_arr)

rand_arr = np.random.uniform(5, 10, size=(5, 3))

print(rand_arr)


[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.931564   0.71448993 0.70050021]
 [0.79967137 0.98515349 0.69637934]
 [0.71556926 0.15051915 0.37184519]
 [0.81690911 0.79321669 0.70375898]
 [0.56734495 0.41035841 0.85413884]]
[[9 8 8]
 [8 5 9]
 [7 8 8]
 [5 6 6]
 [7 9 9]]
[[9.50222978 7.58528312 6.73286295]
 [9.04160859 7.54079861 9.87053905]
 [6.08895667 5.69645448 9.59702358]
 [7.2269475  5.11671335 9.58874568]
 [5.76961805 5.75303219 8.563262  ]]


In [40]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]# 与matlab不同，切片是前闭后开的
print(b)
print(a[0,:])
print(a[1:2,:])# !访问第二行，直接用2是错误的

print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[2 3]
 [6 7]]
[1 2 3 4]
[[5 6 7 8]]
2
77


In [41]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a>2)# 返回布尔数组

[[False False]
 [ True  True]
 [ True  True]]


In [43]:
x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)     # 数据类型

int64


In [53]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x*y)# 标量乘积，相当于matlab的.*
# print(np.dot(x,y))# 乘积
print(x@y)# !新版本乘积
from numpy.linalg import inv
print(x@inv(y))# !乘逆矩阵相当于除法
a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
 
# vdot 将数组展开计算内积
print (np.vdot(a,b))


[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[ 3. -2.]
 [ 2. -1.]]
130


arange和linspace

1、arange(初始值，结束值，间隔) 生成的序列不包含结束值，linspace(初始值, 结束值, 值的个数) 生成的序列包含结束值。

2、如果要使 linspace 和 arrange 等效，可以用 linspace(初始值, 结束值, 值的个数, endpoint = False). 当然，两者有各自的使用场景，尽量不要混用。arrange 适用于知道序列中相邻两数之间的间隔的情况下，比如生成一定范围内奇数或者偶数的序列。linspace 适合序列长度和序列取值范围已知的情况。比如采样频率为1200 Hz, 也就是说 0~1s 之间有1200 个点。


index和语句运行时间测量(ipython的magic函数)

In [68]:
%%time
# 只能置于最上方
x = np.array([[1,  2],  [3,  4],  [5,  6]])
# [0,1,2]代表行索引;[0,1,0]代表列索引
y = x[[0, 1, 2], [0, 1, 0]]
print(y)

x = np.arange(32).reshape((8, 4))
# 分别对应 第4行数据、第2行数据、第1行数据、第7行数据项
print(x[[4, 2, 1, 7]])

# 布尔索引
x = np.array([[0,  1,  2], [3,  4,  5], [6,  7,  8], [9, 10, 11]])
print(x[x > 6])

x = np.ones((2, 3, 4))
# !...代替连续的:,速度更快
%time x[:, :, 0]
%time x[..., 0]
%timeit x[:, :, 0]
# !多次循环更精确
%timeit x[..., 0]


[1 4 5]
[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]
[ 7  8  9 10 11]
CPU times: user 18 µs, sys: 0 ns, total: 18 µs
Wall time: 25 µs
CPU times: user 16 µs, sys: 0 ns, total: 16 µs
Wall time: 23.1 µs
1.02 µs ± 97.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
795 ns ± 50.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
CPU times: user 14.7 s, sys: 52.4 ms, total: 14.7 s
Wall time: 14.9 s


数组变维操作

<table>
<caption>
数组变维操作</caption>
<tbody>
<tr>
<th>
函数名称</th>
<th>
函数介绍</th>
</tr>
<tr>
<td>
reshape</td>
<td>
在不改变数组元素的条件下，修改数组的形状，返回视图</td>
</tr>
<tr>
<td>
flat</td>
<td>
返回是一个迭代器，可以用 for 循环遍历其中的每一个元素。</td>
</tr>
<tr>
<td>
flatten</td>
<td>
以一维数组的形式返回一份数组的副本，对副本的操作不会影响到原数组。</td>
</tr>
<tr>
<td>
ravel</td>
<td>
返回一个连续的扁平数组（即展开的一维数组），与 flatten不同，它返回的是数组视图（修改视图会影响原数组）。</td>
</tr>
<tr>
<td>
resize</td>
<td>
修改原数组</td>
</tbody>
</table>

In [15]:
arr = np.arange(10).reshape(2,-1)# -1表示根据已知的维度推测
print(arr)

# 等价于

arr=np.arange(10)
arr.shape=2,-1
# !等价于arr.resize(2,5)不支持负索引
print(arr)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
a = np.arange(9).reshape(3,3)
for row in a:
    print (row)
#使用flat属性：
for ele in a.flat:
    print (ele,end="，")

print()
print (a.flatten(order = 'F'))

print (a.ravel(order = 'F'))


[0 1 2]
[3 4 5]
[6 7 8]
0，1，2，3，4，5，6，7，8，
[0 3 6 1 4 7 2 5 8]
[0 3 6 1 4 7 2 5 8]


增删改查

<table>
<caption>
数组元素操作方法</caption>
<tbody>
<tr>
<th>
函数名称</th>
<th>
描述说明</th>
</tr>
<tr>
<td>
resize</td>
<td>
返回指定形状的新数组。</td>
</tr>
<tr>
<td>
append</td>
<td>
将元素值添加到数组的末尾。</td>
</tr>
<tr>
<td>
insert</td>
<td>
沿规定的轴将元素值插入到指定的元素前。</td>
</tr>
<tr>
<td>
delete</td>
<td>
删掉某个轴上的子数组，并返回删除后的新数组。</td>
</tr>
<tr>
<td>
argwhere</td>
<td>
返回数组内符合条件的元素的索引值。</td>
</tr>
<tr>
<td>
unique</td>
<td>
用于删除数组中重复的元素，并按元素值由大到小返回一个新数组。</td>
</tr>
</tbody>
</table>

arange

numpy.arange(start, stop, step, dtype = None)

在给定间隔内返回均匀间隔的值。

值在半开区间 [开始，停止)内生成

In [5]:
a=np.arange(1,10,1)
print(a)

[1 2 3 4 5 6 7 8 9]


In [7]:
a[a%2==0]=1
print(a)

[1 1 3 1 5 1 7 1 9]


linspace同matlab，区间前后都闭

叠加

In [16]:
#竖直叠加
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Answers
# Method 1:
np.concatenate([a, b], axis=0)

# Method 2:
np.vstack([a, b])

# Method 3:
np.r_[a, b]

# 水平叠加
# Answers
# Method 1:
np.concatenate([a, b], axis=1)

# Method 2:
np.hstack([a, b])

# Method 3:
np.c_[a, b]

# *第三种最简便


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

axis

In [4]:
import numpy as np
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"
x.sum(axis=0)
x.mean(axis=1)

10
[4 6]
[3 7]


array([1.5, 3.5])

where

where() 函数是另外一个根据条件返回数组中的值的有效方法。只需要把条件传递给它，它就会返回一个使得条件为真的**元素下标**的列表。

In [6]:
a = np.arange(0, 100, 10)
np.where(a < 50)
c = np.where(a >= 50)[0] # !返回符合条件的一维位置数组组成的元组
print(c)
np.where(a > 5,1,-1)# 符合条件的位置设为1，不符合为-1，而且会直接输出



[5 6 7 8 9]


array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

广播机制

这种机制的核心是对形状较小的数组，在横向或纵向上进行一定次数的重复，使其与形状较大的数组拥有相同的维度。

相当于matlab的隐式拓展

遍历

In [12]:
a = np.arange(0,60,5)
a = a.reshape(3,4)
#!使用nditer迭代器,并使用for进行遍历
for x in np.nditer(a):
   print(x)

0
5
10
15
20
25
30
35
40
45
50
55


In [17]:
a = np.arange(0,60,5).reshape(3,4)
#copy方法生成数组副本
for x in np.nditer(a.T.copy(order='C')):# 行优先
    print (x, end=", " )
print()
for x in np.nditer(a.T.copy(order='F')):# 列优先
    print(x,end=", ")
print()
b = np.array([1, 2, 3, 4], dtype = int)
#广播迭代
for x,y in np.nditer([a,b]):
    
    print ("%d:%d" % (x,y),end=",")

0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 
0:1,5:2,10:3,15:4,20:1,25:2,30:3,35:4,40:1,45:2,50:3,55:4,

## 和matlab区别

<iframe src="https://www.numpy.org.cn/user/numpy_for_matlab_users.html#%E7%BA%BF%E6%80%A7%E4%BB%A3%E6%95%B0%E5%8A%9F%E8%83%BD%E5%AF%B9%E5%BA%94%E8%A1%A8" height="500" width="80%">

## 线性代数

<iframe src="https://www.numpy.org.cn/reference/routines/linalg.html#%E7%9F%A9%E9%98%B5%E5%92%8C%E5%90%91%E9%87%8F%E7%A7%AF" height="500" width="80%"></iframe>

## 位运算

<tbody>
<tr>
<th>
序号</th>
<th>
函数</th>
<th>
位运算符</th>
<th>
描述说明</th>
</tr>
<tr>
<td>
1</td>
<td>
bitwise_and</td>
<td>
&amp;</td>
<td>
计算数组元素之间的按位与运算。</td>
</tr>
<tr>
<td>
2</td>
<td>
bitwise_or</td>
<td>
|</td>
<td>
计算数组元素之间的按位或运算。</td>
</tr>
<tr>
<td>
3</td>
<td>
invert</td>
<td>
~</td>
<td>
计算数组元素之间的按位取反运算。</td>
</tr>
<tr>
<td>
4</td>
<td>
left_shift</td>
<td>
&lt;&lt;</td>
<td>
将二进制数的位数向左移。</td>
</tr>
<tr>
<td>
5</td>
<td>
right_shift</td>
<td>
&gt;&gt;</td>
<td>
将二进制数的位数向右移。</td>
</tr>
</tbody>

In [26]:
a = 10 
b = 12 
print("a的二进制数:",bin(a)) 
print("b的二进制数:",bin(b)) 

print("将a与b执行按位与操作:",np.bitwise_and(a,b))  

print("将a与b执行按位与操作:",a&b)  

print(~a)


a的二进制数: 0b1010
b的二进制数: 0b1100
将a与b执行按位与操作: 8
将a与b执行按位与操作: 8
-11


In [31]:
arr = np.array([20,30],dtype = np.uint8) 
print("二进制表示:",np.binary_repr(20,8),np.binary_repr(30,8)) # 限定位数
print(np.invert(arr)) 
print(~arr)
#进行取反操作
print("二进制表示: ", np.binary_repr(235,8),np.binary_repr(225,8))  

二进制表示: 00010100 00011110
[235 225]
[235 225]
二进制表示:  11101011 11100001


## 数学函数



In [33]:

arr = np.array([0, 30, 60, 90]) 
#正弦值数组
sinval = np.sin(arr*np.pi/180) 
print(sinval) 
#计算角度反正弦，返回值以弧度为单位
cosec = np.arcsin(sinval) 
print(cosec) 
#通过degrees函数转化为角度进行验证
print(np.degrees(cosec)) 
#余弦值数组
cosval = np.cos(arr*np.pi/180) 
print(cosval) 
#计算反余弦值，以弧度为单位
sec = np.arccos(cosval) 
print(sec) 
#通过degrees函数转化为角度进行验证
print(np.degrees(sec)) 
#下面是tan()正切函数 
tanval = np.tan(arr*np.pi/180) 
print(tanval) 
cot = np.arctan(tanval) 
print(cot) 
print(np.degrees(cot))  

[0.        0.5       0.8660254 1.       ]
[0.         0.52359878 1.04719755 1.57079633]
[ 0. 30. 60. 90.]
[1.00000000e+00 8.66025404e-01 5.00000000e-01 6.12323400e-17]
[0.         0.52359878 1.04719755 1.57079633]
[ 0. 30. 60. 90.]
[0.00000000e+00 5.77350269e-01 1.73205081e+00 1.63312394e+16]
[0.         0.52359878 1.04719755 1.57079633]
[ 0. 30. 60. 90.]


In [37]:
arr = np.array([12.202, 90.23120, 123.020, 23.202]) 
print(arr) 
print("数组值四舍五入到小数点后两位",np.around(arr, 2)) 
print("数组值四舍五入到小数点后-1位",np.around(arr, -1))  

print (np.floor(arr))


print (np.ceil(arr))

[ 12.202   90.2312 123.02    23.202 ]
数组值四舍五入到小数点后两位 [ 12.2   90.23 123.02  23.2 ]
数组值四舍五入到小数点后-1位 [ 10.  90. 120.  20.]
[ 12.  90. 123.  23.]
[ 13.  91. 124.  24.]


## 统计函数

In [42]:
a = np.arange(10)

print(a.sum()) # >>>45
print(a.min()) # >>>0
print(a.max()) # >>>9
print(a.cumsum()) # >>>[ 0  1  3  6 10 15 21 28 36 45]

45
0
9
[ 0  1  3  6 10 15 21 28 36 45]


<img src="https://i.stack.imgur.com/Z29Nn.jpg">

In [45]:

a = np.array([[3,7,5],[8,4,3],[2,4,9]]) 
print ('数组a是：')
print(a)
#amin()函数
print (np.amin(a))
#调用 amin() 函数，axis=1
print(np.amin(a,1))
#调用amax()函数
print(np.amax(a))

#再次调用amax()函数
print(np.amax(a,0))# !求出来是各列数组的统计量，按行，跨列

数组a是：
[[3 7 5]
 [8 4 3]
 [2 4 9]]
2
[3 3 2]
9
[8 7 9]


In [14]:
a = np.array([[2,10,20],[80,43,31],[22,43,10]]) 
print("原数组",a) 
print("沿着axis 1:",np.ptp(a,1)) 
print("沿着axis 0:",np.ptp(a,0)) 

原数组 [[ 2 10 20]
 [80 43 31]
 [22 43 10]]
沿着axis 1: [18 49 33]
沿着axis 0: [[78 33 21]]


In [24]:
a=np.array([3,1,2,4,6,1])
print(np.amax(a,0))


6


In [23]:
a=np.ones([2,3,4,5])
print()
print(np.sum(a,0))
print(np.sum(a,1))
print(np.sum(a,2)) 


# *返回的矩阵类型是原维度除去axis的维度


[[[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]

 [[2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]
  [2. 2. 2. 2. 2.]]]
[[[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]

 [[3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]
  [3. 3. 3. 3. 3.]]]
[[[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]

 [[4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]
  [4. 4. 4. 4. 4.]]]


## 排序和搜索

In [3]:
a = np.array([[3,7],[9,1]]) 
print('a数组是：')
print(a)
#调用sort()函数
print(np.sort(a))
#按列排序：
print(np.sort(a, axis = 0))
#设置在sort函数中排序字段
dt = np.dtype([('name',  'S10'),('age',  int)])
a = np.array([("raju",21),("anil",25),("ravi",  17),  ("amar",27)], dtype = dt) 
#再次打印a数组
print(a)
#按name字段排序
print(np.sort(a, order = 'name'))

a数组是：
[[3 7]
 [9 1]]
[[3 7]
 [1 9]]
[[3 1]
 [9 7]]
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [4]:
# argsort() 沿着指定的轴，对输入数组的元素值进行排序，并返回排序后的元素索引数组。
a = np.array([90, 29, 89, 12]) 
print("原数组",a) 
sort_ind = np.argsort(a) 
print("打印排序元素索引值",sort_ind) 
#!使用索引数组对原数组排序
sort_a = a[sort_ind] 
print("打印排序数组") 
for i in sort_ind: 
    print(a[i],end = " ")  

原数组 [90 29 89 12]
打印排序元素索引值 [3 1 2 0]
打印排序数组
12 29 89 90 

In [5]:
# numpy.lexsort() 按键序列对数组进行排序，它返回一个已排序的索引数组，类似于 numpy.argsort()。
a = np.array(['a','b','c','d','e']) 
b = np.array([12, 90, 380, 12, 211]) 
ind = np.lexsort((a,b)) 
#打印排序元素的索引数组
print(ind) 
#使用索引数组对数组进行排序
for i in ind: 
    print(a[i],b[i])  

[0 3 1 4 2]
a 12
d 12
b 90
e 211
c 380


In [9]:
# !相当于filter

x = np.arange(9.).reshape(3, 3)
print(x) 
#设置条件选择偶数元素
condition = np.mod(x,2)== 0
#输出布尔值数组
print(condition)
#按condition提取满足条件的元素值
print (np.extract(condition, x))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ True False  True]
 [False  True False]
 [ True False  True]]
[0. 2. 4. 6. 8.]


In [11]:
# 返回最大值索引
a = np.array([[30,40,70],[80,20,10],[50,90,60]]) 
#a数组
print (a)
#argmax() 函数
print (np.argmax(a))
#将数组以一维展开
print (a.flatten())
#沿轴 0 的最大值索引：
maxindex = np.argmax(a, axis =  0) 
print (maxindex)
#沿轴 1 的最大值索引
maxindex = np.argmax(a, axis =  1) 
print (maxindex) 

[[30 40 70]
 [80 20 10]
 [50 90 60]]
7
[30 40 70 80 20 10 50 90 60]
[1 2 0]
[2 0 1]


## 副本和视图

In [75]:
import numpy as np 
a = np.array([[1,2,3,4],[9,0,2,3],[1,2,3,19]]) 
print("原数组",a) 
print("数组a的ID:",id(a)) 
b = a.view() 
print("数组b的ID:",id(b)) 
#打印b数组
print(b) 
#改变b数组形状
b.shape = 4,3
print("原数组a",a) # !不影响原数组的形状
print("新数组b",b) 
b[0,0]=10

print(f'修改b后a的值{a}')# !被改变，说明共享同一段内存


原数组 [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
数组a的ID: 140102181481248
数组b的ID: 140102181548640
[[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
原数组a [[ 1  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
新数组b [[ 1  2  3]
 [ 4  9  0]
 [ 2  3  1]
 [ 2  3 19]]
修改b后a的值[[10  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]


In [22]:
b = a
c = a[()]
d = a[:]
e = a.copy()
print('a:', hex(id(a)), '\n', a)# !查看内存
print('b:', hex(id(b)), '\n', b)
print('c:', hex(id(c)), '\n', c)
print('d:', hex(id(d)), '\n', d)
print('e:', hex(id(e)), '\n', e)
# 除了直接复制都位于不同的位置


a: 0x7f6c15714c10 
 [[10  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
b: 0x7f6c15714c10 
 [[10  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
c: 0x7f6c1564a990 
 [[10  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
d: 0x7f6c1564abc0 
 [[10  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
e: 0x7f6c156988f0 
 [[10  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]


In [23]:
a -= 5
print('a:', hex(id(a)), '\n', a)
print('b:', hex(id(b)), '\n', b)
print('c:', hex(id(c)), '\n', c)
print('d:', hex(id(d)), '\n', d)
print('e:', hex(id(e)), '\n', e)
# !除了copy都改变了,copy是深拷贝

a: 0x7f6c15714c10 
 [[ 5 -3 -2 -1]
 [ 4 -5 -3 -2]
 [-4 -3 -2 14]]
b: 0x7f6c15714c10 
 [[ 5 -3 -2 -1]
 [ 4 -5 -3 -2]
 [-4 -3 -2 14]]
c: 0x7f6c1564a990 
 [[ 5 -3 -2 -1]
 [ 4 -5 -3 -2]
 [-4 -3 -2 14]]
d: 0x7f6c1564abc0 
 [[ 5 -3 -2 -1]
 [ 4 -5 -3 -2]
 [-4 -3 -2 14]]
e: 0x7f6c156988f0 
 [[10  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]


In [76]:
print('a-b share mem:', np.may_share_memory(a,b))
print('a-c share mem:', np.may_share_memory(a,c))
print('a-d share mem:', np.may_share_memory(a,d))
print('a-e share mem:', np.may_share_memory(a,e))
# !说明c,d都是视窗view
c.shape=1,-1
d.shape=2,-1
# !都对a的形状无影响
print(a)
%timeit x=a[:]
%timeit x=a[()]

a-b share mem: True
a-c share mem: False
a-d share mem: False
a-e share mem: False
[[10  2  3  4]
 [ 9  0  2  3]
 [ 1  2  3 19]]
530 ns ± 45.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
396 ns ± 33.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


用arr\[()]和arr\[:]代替view()更简便 前者更快